# Generated by Django 5.1.1 on 2024-10-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='city',
            field=models.CharField(default='Cidade Desconhecida', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='state',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais')], default='cidade desconhecida', max_length=2),
        ),
    ]
