# Generated by Django 5.1.2 on 2024-10-14 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_shelter_city_shelter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='cep',
            field=models.CharField(default='00000-000', max_length=8, validators=[django.core.validators.RegexValidator(message='O CEP deve ter 8 dígitos.', regex='^\\d{8}$')]),
            preserve_default=False,
        ),
    ]
