# Generated by Django 5.1.2 on 2024-10-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_shelter_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shelter_photos/'),
        ),
    ]
