# Generated by Django 5.1.2 on 2024-10-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_shelter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
