# Generated by Django 5.1.1 on 2024-10-03 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('porte', models.CharField(max_length=20)),
                ('colour', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/')),
                ('date_rescue', models.DateField(auto_now_add=True)),
                ('adopted', models.BooleanField(default=False)),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelter.shelter')),
            ],
        ),
    ]
