# Generated by Django 5.1.4 on 2025-01-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato'), ('A', 'Aves')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande')], max_length=1),
        ),
    ]
