# Generated by Django 5.1.1 on 2024-10-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoption',
            old_name='date_of_birth',
            new_name='date_of_adoption',
        ),
    ]
