# Generated by Django 5.1.1 on 2024-10-03 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Máximo de 15 dígitos.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais')], max_length=2)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='O CEP deve ter 8 dígitos.', regex='^\\d{8}$')])),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
