# Generated by Django 5.1.1 on 2024-10-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
