# Generated by Django 5.1.2 on 2024-10-14 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0002_alter_adopter_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9, validators=[django.core.validators.RegexValidator(message='O CEP deve ter 8 dígitos.', regex='^\\d{8}$')]),
        ),
    ]
